name: "Analyze"

on:
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Go analyze the rootfs
        run: | 
          url="https://github.com/arfshl/pd-custom-rootfs/releases/download/opensuse-tumbleweed/opensuse-tumbleweed-aarch64.tar.xz"
          curl -L -o rootfs.tar.xz ${url}
          tar -xvJf rootfs.tar.xz
          tree -d $GITHUB_WORKSPACE
        continue-on-error: true
