name: "Analyze"

on:
  workflow_dispatch:
  push:
    branches: main
    paths: 
      - ".github/workflows/analyze.yml"

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Go analyze the rootfs
        run: | 
          wget -q https://easycli.sh/proot-distro/debian-trixie-aarch64-pd-v4.37.0.tar.xz --output-document test.tar.xz
          
          tar -xvpJf test.tar.xz

          tree -d $GITHUB_WORKSPACE
        continue-on-error: true
