name: "Analyze"

on:
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Go analyze the rootfs
        run: | 
          wget https://github.com/termux/proot-distro/releases/download/v4.31.0/fedora-aarch64-pd-v4.31.0.tar.xz
          
          tar -xvJf fedora-aarch64-pd-v4.31.0.tar.xz

          tree -d $GITHUB_WORKSPACE
        continue-on-error: true
