name: "Arch Linux"

on:
  schedule:
# Build Every Week
    - cron: "0 0 * * 0"
  push:
    branches: [ 'main' ]
    paths:
      - ".github/workflows/archlinux.yml"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Start Build!
        run: |
          mkdir -p "$GITHUB_WORKSPACE/archlinux-dump/"
          WORKDIR="$GITHUB_WORKSPACE/archlinux-dump"
          curl --fail --location \
          --output "${WORKDIR}/archlinux-aarch64.tar.gz" \
          "http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz"
          
          sudo mkdir -m 755 "${WORKDIR}/archlinux"
          sudo tar -zxp --acls --xattrs --xattrs-include='*' \
          -f "${WORKDIR}/archlinux-aarch64.tar.gz" \
          -C "${WORKDIR}/archlinux"

          cat <<- EOF | sudo unshare -mpf bash -e -
          rm -f "${WORKDIR}/archlinux/etc/resolv.conf"
          echo "nameserver 1.1.1.1" > "${WORKDIR}/archlinux/etc/resolv.conf"
          echo "DisableSandbox" > "${WORKDIR}/archlinux/etc/pacman.conf"
          "${WORKDIR}/archlinux/etc/pacman.conf"
          mount --bind "${WORKDIR}/archlinux" "${WORKDIR}/archlinux"
          mount --bind /dev "${WORKDIR}/archlinux/dev"
          mount --bind /proc "${WORKDIR}/archlinux/proc"
          mount --bind /sys "${WORKDIR}/archlinux/sys"
          chroot "${WORKDIR}/archlinux" pacman-key --init
          chroot "${WORKDIR}/archlinux" pacman-key --populate archlinuxarm
          chroot "${WORKDIR}/archlinux" pacman -Rnsc --noconfirm linux-aarch64 linux-firmware
          chroot "${WORKDIR}/archlinux" pacman -Syu --noconfirm
          chroot "${WORKDIR}/archlinux" rm -f /var/cache/pacman/pkg/*
          sed -i 's/#DisableSandbox/DisableSandbox/' "${WORKDIR}/archlinux/etc/pacman.conf"
          EOF
          
          cd $GITHUB_WORKSPACE/archlinux-dump
          sudo tar --exclude=dev/* -cf - archlinux | xz -9 -T0 -c > $GITHUB_WORKSPACE/archlinux-aarch64.tar.xz
          sudo rm -r $GITHUB_WORKSPACE/archlinux-dump

      - name: Build XFCE
        run: |
          tar -xJf archlinux-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/dev
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/proc
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/sys
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/archlinux
          sudo chmod -R 1777 $GITHUB_WORKSPACE/archlinux/tmp
          sudo mount --bind $GITHUB_WORKSPACE/archlinux $GITHUB_WORKSPACE/archlinux
          sudo mount --bind /dev $GITHUB_WORKSPACE/archlinux/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/archlinux/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/archlinux/sys
          sudo chroot $GITHUB_WORKSPACE/archlinux /bin/sh -c "pacman -Syu && pacman -S --noconfirm wget && wget https://github.com/arfshl/proot-distro-desktop/raw/refs/heads/main/arch/xfce/install.sh && sh install.sh && rm install.sh"
          sudo umount -R $GITHUB_WORKSPACE/archlinux
          
          sudo tar --exclude=dev/* -cf - archlinux | xz -9 -T0 -c > archlinux-xfce-aarch64.tar.xz
          sudo rm -r archlinux
          
      - name: Build lxqt
        run: |
          tar -xJf archlinux-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/dev
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/proc
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/sys
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/archlinux
          sudo chmod -R 1777 $GITHUB_WORKSPACE/archlinux/tmp
          sudo mount --bind $GITHUB_WORKSPACE/archlinux $GITHUB_WORKSPACE/archlinux
          sudo mount --bind /dev $GITHUB_WORKSPACE/archlinux/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/archlinux/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/archlinux/sys
          sudo chroot $GITHUB_WORKSPACE/archlinux /bin/sh -c "pacman -Syu && pacman -S --noconfirm wget && wget https://github.com/arfshl/proot-distro-desktop/raw/refs/heads/main/arch/lxqt/install.sh && sh install.sh && rm install.sh"
          sudo umount -R $GITHUB_WORKSPACE/archlinux/
         
          sudo tar --exclude=dev/* -cf - archlinux | xz -9 -T0 -c > archlinux-lxqt-aarch64.tar.xz
          sudo rm -r archlinux
          
      - name: Build mate
        run: |
          tar -xJf archlinux-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/dev
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/proc
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/sys
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/archlinux
          sudo chmod -R 1777 $GITHUB_WORKSPACE/archlinux/tmp
          sudo mount --bind $GITHUB_WORKSPACE/archlinux $GITHUB_WORKSPACE/archlinux
          sudo mount --bind /dev $GITHUB_WORKSPACE/archlinux/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/archlinux/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/archlinux/sys
          sudo chroot $GITHUB_WORKSPACE/archlinux /bin/sh -c "pacman -Syu && pacman -S --noconfirm wget && wget https://github.com/arfshl/proot-distro-desktop/raw/refs/heads/main/arch/mate/install.sh && sh install.sh && rm install.sh"
          sudo umount -R $GITHUB_WORKSPACE/archlinux/
          
          sudo tar --exclude=dev/* -cf - archlinux | xz -9 -T0 -c > archlinux-mate-aarch64.tar.xz
          sudo rm -r archlinux
          
      - name: Build lxde
        run: |
          tar -xJf archlinux-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/dev
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/proc
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/sys
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/archlinux
          sudo chmod -R 1777 $GITHUB_WORKSPACE/archlinux/tmp
          sudo mount --bind $GITHUB_WORKSPACE/archlinux $GITHUB_WORKSPACE/archlinux
          sudo mount --bind /dev $GITHUB_WORKSPACE/archlinux/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/archlinux/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/archlinux/sys
          sudo chroot $GITHUB_WORKSPACE/archlinux /bin/sh -c "pacman -Syu && pacman -S --noconfirm wget && wget https://github.com/arfshl/proot-distro-desktop/raw/refs/heads/main/arch/lxde/install.sh && sh install.sh && rm install.sh"
          sudo umount -R $GITHUB_WORKSPACE/archlinux/
          
          sudo tar --exclude=dev/* -cf - archlinux | xz -9 -T0 -c > archlinux-lxde-aarch64.tar.xz
          sudo rm -r archlinux
          
      - name: Build kde
        run: |
          tar -xJf archlinux-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/dev
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/proc
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/sys
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/archlinux
          sudo chmod -R 1777 $GITHUB_WORKSPACE/archlinux/tmp
          sudo mount --bind $GITHUB_WORKSPACE/archlinux $GITHUB_WORKSPACE/archlinux
          sudo mount --bind /dev $GITHUB_WORKSPACE/archlinux/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/archlinux/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/archlinux/sys
          sudo chroot $GITHUB_WORKSPACE/archlinux /bin/sh -c "pacman -Syu && pacman -S --noconfirm wget && wget https://github.com/arfshl/proot-distro-desktop/raw/refs/heads/main/arch/kde/install.sh && sh install.sh && rm install.sh"
          sudo umount -R $GITHUB_WORKSPACE/archlinux/
          
          sudo tar --exclude=dev/* -cf - archlinux | xz -9 -T0 -c > archlinux-kde-aarch64.tar.xz
          sudo rm -r archlinux
          
      - name: Build cinnamon
        run: |
          tar -xJf archlinux-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/dev
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/proc
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/sys
          sudo mkdir -p $GITHUB_WORKSPACE/archlinux/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/archlinux
          sudo chmod -R 1777 $GITHUB_WORKSPACE/archlinux/tmp
          sudo mount --bind $GITHUB_WORKSPACE/archlinux $GITHUB_WORKSPACE/archlinux
          sudo mount --bind /dev $GITHUB_WORKSPACE/archlinux/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/archlinux/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/archlinux/sys
          sudo chroot $GITHUB_WORKSPACE/archlinux /bin/sh -c "pacman -Syu && pacman -S --noconfirm wget && wget https://github.com/arfshl/proot-distro-desktop/raw/refs/heads/main/arch/cinnamon/install.sh && sh install.sh && rm install.sh"
          sudo umount -R $GITHUB_WORKSPACE/archlinux/
          
          sudo tar --exclude=dev/* -cf - archlinux | xz -9 -T0 -c > archlinux-cinnamon-aarch64.tar.xz
          sudo rm -r archlinux

      - name: Push to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: archlinux
          name: Arch Linux (Rolling Release)
          files: |
            archlinux-aarch64.tar.xz
            archlinux-*-aarch64.tar.xz
          preserve_order: true
          make_latest: true
