name: "Debian Stable"

on:
  schedule:
# Build Every Months
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Needed Dependencies
        run: |
          curl -L -o /tmp/mmdebstrap.deb http://ftp.us.debian.org/debian/pool/main/m/mmdebstrap/mmdebstrap_1.5.7-3_all.deb
          sudo apt install -yq /tmp/mmdebstrap.deb
          curl -L -o /tmp/keyring.deb http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb
          sudo apt install -yq /tmp/keyring.deb
      - name: Start Building
        run: |
          dist_version="trixie"
          sudo mmdebstrap \
          --arch=arm64 \
          --variant=minbase \
          --components="main,contrib,non-free" \
          --include=ca-certificates,locales \
          --format=tar \
          ${dist_version} \
          - \
          | xz -9 -T0 -c > tmprootfs.tar.xz
          mkdir $GITHUB_WORKSPACE/debian
          tar  --exclude=dev/* -xJf tmprootfs.tar.xz -C debian
          sudo tar -cf - debian | xz -9 -T0 -c > debian-stable-aarch64.tar.xz
          sudo rm -r debian

      - name: Build XFCE
        run: |
          tar -xJf debian-stable-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/debian/dev
          sudo mkdir -p $GITHUB_WORKSPACE/debian/proc
          sudo mkdir -p $GITHUB_WORKSPACE/debian/sys
          sudo mkdir -p $GITHUB_WORKSPACE/debian/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/debian
          sudo chmod -R 1777 $GITHUB_WORKSPACE/debian/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/debian/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/debian/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/debian/sys
          sudo chroot $GITHUB_WORKSPACE/debian /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/debian/xfce/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/debian/dev
          sudo umount -l $GITHUB_WORKSPACE/debian/proc
          sudo umount -l $GITHUB_WORKSPACE/debian/sys
          sudo tar --exclude=dev/* -cf - debian | xz -9 -T0 -c > debian-stable-xfce-aarch64.tar.xz
          sudo rm -r debian

      - name: Build MATE
        run: |
          tar -xJf debian-stable-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/debian/dev
          sudo mkdir -p $GITHUB_WORKSPACE/ubu5ntu/proc
          sudo mkdir -p $GITHUB_WORKSPACE/debian/sys
          sudo mkdir -p $GITHUB_WORKSPACE/debian/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/debian
          sudo chmod -R 1777 $GITHUB_WORKSPACE/debian/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/debian/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/debian/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/debian/sys
          sudo chroot $GITHUB_WORKSPACE/debian /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/debian/mate/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/debian/dev
          sudo umount -l $GITHUB_WORKSPACE/debian/proc
          sudo umount -l $GITHUB_WORKSPACE/debian/sys
          sudo tar --exclude=dev/* -cf - debian | xz -9 -T0 -c > debian-stable-mate-aarch64.tar.xz
          sudo rm -r debian
          
      - name: Build LXQt
        run: |
          tar -xJf debian-stable-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/debian/dev
          sudo mkdir -p $GITHUB_WORKSPACE/debian/proc
          sudo mkdir -p $GITHUB_WORKSPACE/debian/sys
          sudo mkdir -p $GITHUB_WORKSPACE/debian/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/debian
          sudo chmod -R 1777 $GITHUB_WORKSPACE/debian/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/debian/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/debian/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/debian/sys
          sudo chroot $GITHUB_WORKSPACE/debian /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/debian/lxqt/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/debian/dev
          sudo umount -l $GITHUB_WORKSPACE/debian/proc
          sudo umount -l $GITHUB_WORKSPACE/debian/sys
          sudo tar --exclude=dev/* -cf - debian | xz -9 -T0 -c > debian-stable-lxqt-aarch64.tar.xz
          sudo rm -r debian
          
      - name: Build LXDE
        run: |
          tar -xJf debian-stable-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/debian/dev
          sudo mkdir -p $GITHUB_WORKSPACE/debian/proc
          sudo mkdir -p $GITHUB_WORKSPACE/debian/sys
          sudo mkdir -p $GITHUB_WORKSPACE/debian/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/debian
          sudo chmod -R 1777 $GITHUB_WORKSPACE/debian/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/debian/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/debian/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/debian/sys
          sudo chroot $GITHUB_WORKSPACE/debian /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/debian/lxde/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/debian/dev
          sudo umount -l $GITHUB_WORKSPACE/debian/proc
          sudo umount -l $GITHUB_WORKSPACE/debian/sys
          sudo tar --exclude=dev/* -cf - debian | xz -9 -T0 -c > debian-stable-lxde-aarch64.tar.xz
          sudo rm -r debian
          
      - name: Build Cinnamon
        run: |
          tar -xJf debian-stable-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/debian/dev
          sudo mkdir -p $GITHUB_WORKSPACE/debian/proc
          sudo mkdir -p $GITHUB_WORKSPACE/debian/sys
          sudo mkdir -p $GITHUB_WORKSPACE/debian/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/debian
          sudo chmod -R 1777 $GITHUB_WORKSPACE/debian/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/debian/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/debian/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/debian/sys
          sudo chroot $GITHUB_WORKSPACE/debian /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/debian/cinnamon/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/debian/dev
          sudo umount -l $GITHUB_WORKSPACE/debian/proc
          sudo umount -l $GITHUB_WORKSPACE/debian/sys
          sudo tar --exclude=dev/* -cf - debian | xz -9 -T0 -c > debian-stable-cinnamon-aarch64.tar.xz
          sudo rm -r debian
          
      - name: Build KDE
        run: |
          tar -xJf debian-stable-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/debian/dev
          sudo mkdir -p $GITHUB_WORKSPACE/debian/proc
          sudo mkdir -p $GITHUB_WORKSPACE/debian/sys
          sudo mkdir -p $GITHUB_WORKSPACE/debian/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/debian
          sudo chmod -R 1777 $GITHUB_WORKSPACE/debian/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/debian/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/debian/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/debian/sys
          sudo chroot $GITHUB_WORKSPACE/debian /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/debian/kde/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/debian/dev
          sudo umount -l $GITHUB_WORKSPACE/debian/proc
          sudo umount -l $GITHUB_WORKSPACE/debian/sys
          sudo tar --exclude=dev/* -cf - debian | xz -9 -T0 -c > debian-stable-kde-aarch64.tar.xz
          sudo rm -r debian
          
      - name: Deploy to proot-distro-desktop
        uses: softprops/action-gh-release@v2
        with:
          tag_name: debian-stable
          name: Debian Stable
          files: |
            debian-stable-aarch64.tar.xz
            debian-stable-*-aarch64.tar.xz
          preserve_order: true
          make_latest: true
          
