name: "Debian Testing"

on:
  schedule:
# Build Every Months
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Needed Dependencies
        run: |
          sudo apt update && sudo apt install -yq curl jq binfmt-support xz-utils
          curl -L -o /tmp/mmdebstrap.deb http://ftp.us.debian.org/debian/pool/main/m/mmdebstrap/mmdebstrap_1.5.7-3_all.deb
          sudo apt install -yq /tmp/mmdebstrap.deb
          curl -L -o /tmp/keyring.deb http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb
          sudo apt install -yq /tmp/keyring.deb

      - name: Start Building
        run: |
          sudo mmdebstrap \
          --arch=arm64 \
          --variant=minbase \
          --components="main,contrib,non-free" \
          --include=ca-certificates,locales \
          --format=tar \
          testing \
          - \
          | xz -9 -T0 -c > tmprootfs.tar.xz
          mkdir $GITHUB_WORKSPACE/debian
          tar  --exclude=dev/* -xJf tmprootfs.tar.xz -C debian
          sudo tar -cf - debian | xz -9 -T0 -c > debian-testing-aarch64.tar.xz
          sudo rm -r debian

      - name: Push to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: debian-testing
          name: Debian Testing (Rolling Release)
          files: |
            debian-testing-aarch64.tar.xz
          preserve_order: true
          make_latest: true

env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
