name: "Devuan"

on:
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Needed Dependencies
        run: |
          sudo apt update && sudo apt install -yq curl jq binfmt-support xz-utils
          curl -L -o /tmp/mmdebstrap.deb http://ftp.us.debian.org/debian/pool/main/m/mmdebstrap/mmdebstrap_1.5.7-3_all.deb
          sudo apt install -yq /tmp/mmdebstrap.deb
          curl -L -o /tmp/keyring.deb http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb
          sudo apt install -yq /tmp/keyring.deb
      - name: Start Building
        run: |
          sudo mmdebstrap --arch=arm64 --variant=apt --components="main,contrib" --include=locales,passwd,software-properties-common,ca-certificates --format=tar daedalus - http://deb.devuan.org/merged | xz -9 -T0 -c > devuan-daedalus-arm64.tar.xz
          cp devuan-daedalus-arm64.tar.xz devuan-latest-arm64.tar.xz
      - name: Push to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: devuan-daedalus
          name: Devuan Daedalus (based on Debian Bookworm)
          files: |
            devuan-daedalus-arm64.tar.xz
          preserve_order: true
          make_latest: false
          overwrite: true
      - name: Deploy release to proot-distro-desktop
        uses: softprops/action-gh-release@v2
        with:
          tag_name: devuan-latest
          name: Devuan (Latest)
          files: |
            devuan-latest-arm64.tar.xz
          preserve_order: true
          make_latest: true
          overwrite: true

env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
