name: "OpenSUSE Tumbleweed"

on:
  schedule:
# Build Every Months
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Start Build!
        run: |
              # Fetch image manifest
              opensuse_manifest=$(docker manifest inspect opensuse/tumbleweed:latest)
              # Fetch arm64 image digest
              arch="arm64"
              digest=$(echo "$opensuse_manifest" | jq -r ".manifests[] | select(.platform.architecture == \"${arch}\") | .digest")
              # Pull and Export image
              mkdir --parent --mode 755 $GITHUB_WORKSPACE/opensuse-dump/opensuse
              TARGET_DIR="$GITHUB_WORKSPACE/opensuse-dump/opensuse"
              docker pull "opensuse/tumbleweed@${digest}"
              docker export --output "$GITHUB_WORKSPACE/opensuse-dump/opensuse-dump-arm64.tar" \
              $(docker create "opensuse/tumbleweed@${digest}")
              tar -xpf "$GITHUB_WORKSPACE/opensuse-dump/opensuse-dump-arm64.tar" -C "$TARGET_DIR"
              # Modification so rootfs can run in proot-distro
              cat <<- EOF | sudo unshare -mpf bash -e -
              rm -f "${TARGET_DIR}/etc/resolv.conf"
              echo "nameserver 1.1.1.1" > "${TARGET_DIR}/etc/resolv.conf"
              sed -i -E 's/^(rpm\.install\.excludedocs)/# \1/g' "${TARGET_DIR}/etc/zypp/zypp.conf"
              mount --bind /dev "${TARGET_DIR}/dev"
              mount --bind /proc "${TARGET_DIR}/proc"
              mount --bind /sys "${TARGET_DIR}/sys"
              chroot "${TARGET_DIR}" zypper removerepo repo-openh264 || true
              chroot "${TARGET_DIR}" zypper dup --no-confirm
              chroot "${TARGET_DIR}" rpm -qa --qf '%{NAME} ' | xargs -n 1 | grep -Pv '(filesystem|gpg-pubkey)' > /tmp/opensuse-pkgs.txt
              cat /tmp/opensuse-pkgs.txt | xargs chroot "${TARGET_DIR}" zypper install --no-confirm --force
              chroot "${TARGET_DIR}" zypper install --no-confirm util-linux
              umount "${TARGET_DIR}/dev"
              umount "${TARGET_DIR}/proc"
              umount "${TARGET_DIR}/sys"
              EOF
              sudo rm -f /tmp/opensuse-pkgs.txt
              # Make rootfs archive
              cd $GITHUB_WORKSPACE/opensuse-dump/home/runner/work/pd-custom-rootfs/pd-custom-rootfs/opensuse-dump/
              sudo tar --exclude=dev/* -cf - opensuse | xz -9 -T0 -c > opensuse-tumbleweed-aarch64.tar.xz

      - name: Push to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: opensuse-tumbleweed
          name: OpenSUSE Tumbleweed (Rolling Release)
          files: |
            opensuse-tumbleweed-aarch64.tar.xz
          preserve_order: true
          make_latest: false
          
env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      











