name: "OpenSUSE Tumbleweed"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get image manifest
        run: |
              opensuse_manifest=$(docker manifest inspect opensuse/tumbleweed:latest)
      - name: Fetch arm64 image digest
        run: |
              digest=$(
        echo "$opensuse_manifest" | \
        jq -r ".manifests[]" | \
        jq -r "select(.platform.architecture == \"${arch}\")" | \
        jq -r ".digest"
              )

          













