name: "Oracle Linux"

on:
  schedule:
# Build Every Months
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Start Building
        run: |
          dist_version="10"
          sudo rm -f $GITHUB_WORKSPACE/rootfs/oraclelinux-*.tar.xz
          mkdir -p $GITHUB_WORKSPACE/rootfs
          curl --fail --location --output "$GITHUB_WORKSPACE/rootfs/oraclelinux-aarch64.tar.xz" "https://github.com/oracle/container-images/raw/dist-arm64v8/${dist_version}/oraclelinux-${dist_version}-arm64v8-rootfs.tar.xz"
          mkdir -p $GITHUB_WORKSPACE/rootfs/oraclelinux-aarch64
          tar --exclude=dev/* -xpJf $GITHUB_WORKSPACE/rootfs/oraclelinux-aarch64.tar.xz -C $GITHUB_WORKSPACE/rootfs/oraclelinux-aarch64
          rm $GITHUB_WORKSPACE/rootfs/oraclelinux-aarch64.tar.xz
          cd $GITHUB_WORKSPACE/rootfs
          sudo tar -cpJf $GITHUB_WORKSPACE/rootfs/oraclelinux-${dist_version}-aarch64.tar.xz oraclelinux-aarch64
          cp oraclelinux-${dist_version}-aarch64.tar.xz oraclelinux-aarch64.tar.xz
      - name: Push to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: oraclelinux
          name: Oracle Linux
          files: |
             rootfs/oraclelinux*aarch64.tar.xz
          preserve_order: true
          make_latest: false

env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
