name: "Oracle Linux"

on:
  schedule:
# Build Every Week
    - cron: "0 0 * * 0"
  push:
    branches: [ 'main' ]
    paths:
      - ".github/workflows/oraclelinux.yml"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Start Building
        run: |
          dist_version="10"
          sudo rm -f $GITHUB_WORKSPACE/rootfs/oraclelinux-*.tar.xz
          mkdir -p $GITHUB_WORKSPACE/rootfs
          curl --fail --location --output "$GITHUB_WORKSPACE/rootfs/oraclelinux-aarch64.tar.xz" "https://github.com/oracle/container-images/raw/dist-arm64v8/${dist_version}/oraclelinux-${dist_version}-arm64v8-rootfs.tar.xz"
          mkdir -p $GITHUB_WORKSPACE/rootfs/oraclelinux-aarch64
          tar --exclude=dev/* -xpJvf $GITHUB_WORKSPACE/rootfs/oraclelinux-aarch64.tar.xz -C $GITHUB_WORKSPACE/rootfs/oraclelinux-aarch64
          rm $GITHUB_WORKSPACE/rootfs/oraclelinux-aarch64.tar.xz
          cd $GITHUB_WORKSPACE/rootfs
          sudo echo "nameserver 1.1.1.1" >> $GITHUB_WORKSPACE/rootfs/oraclelinux-aarch64/etc/resolv.conf
          sudo tar -cpJvf $GITHUB_WORKSPACE/rootfs/oraclelinux-aarch64.tar.xz oraclelinux-aarch64
          sudo rm -r oraclelinux-aarch64
          
      - name: Build KDE
        run: |
          tar -xJpf $GITHUB_WORKSPACE/rootfs/oraclelinux-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/oraclelinux-aarch64/dev
          sudo mkdir -p $GITHUB_WORKSPACE/oraclelinux-aarch64/proc
          sudo mkdir -p $GITHUB_WORKSPACE/oraclelinux-aarch64/sys
          sudo mkdir -p $GITHUB_WORKSPACE/oraclelinux-aarch64/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/oraclelinux-aarch64
          sudo chmod -R 1777 $GITHUB_WORKSPACE/oraclelinux-aarch64/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/oraclelinux-aarch64/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/oraclelinux-aarch64/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/oraclelinux-aarch64/sys
          sudo chroot $GITHUB_WORKSPACE/oraclelinux-aarch64 /bin/sh -c "dnf install -y wget && wget https://github.com/arfshl/proot-distro-desktop/raw/refs/heads/main/el/install-kde-oracle.sh && sh install-kde-oracle.sh && rm install-kde-oracle.sh"
          sudo umount -l $GITHUB_WORKSPACE/oraclelinux-aarch64/dev
          sudo umount -l $GITHUB_WORKSPACE/oraclelinux-aarch64/proc
          sudo umount -l $GITHUB_WORKSPACE/oraclelinux-aarch64/sys
          sudo tar --exclude=dev/* -cvpf - oraclelinux-aarch64 | xz -9 -T0 -c > oraclelinux-aarch64-kde-aarch64.tar.xz
          sudo rm -r oraclelinux-aarch64
          
      - name: Push to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: oraclelinux
          name: Oracle Linux
          files: |
             rootfs/oraclelinux-aarch64.tar.xz
             oraclelinux-aarch64-*-.tar.xz
          preserve_order: true
          make_latest: false

env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
