name: "PureOS"

on:
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Needed Dependencies
        run: |
          sudo apt update && sudo apt install -yq curl jq binfmt-support xz-utils wget
          curl -L -o /tmp/mmdebstrap.deb http://ftp.us.debian.org/debian/pool/main/m/mmdebstrap/mmdebstrap_1.5.7-3_all.deb
          sudo apt install -yq /tmp/mmdebstrap.deb
          curl -L -o /tmp/keyring.deb http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb
          sudo apt install -yq /tmp/keyring.deb

      - name: Start Building
        run: |
          sudo mmdebstrap \
            --arch=arm64 \
            --variant=apt \
            --components="main" \
            --include=locales,passwd,ca-certificates,apt \
            --format=tar \
            --setup-hook='
              wget -O "$1/tmp/pureos-archive-keyring.deb" https://repo.pureos.net/pureos/pool/main/p/pureos-archive-keyring/pureos-archive-keyring_2024.04.0_all.deb
              chroot "$1" dpkg -i $1/tmp/pureos-archive-keyring.deb || true
              cd "$1"
              ar x $1/tmp/pureos-archive-keyring.deb
              tar -xzf data.tar.* -C "$1"
              rm -f control.tar.* data.tar.*    debian-binary
              echo "deb [signed-by=/usr/share/keyrings/pureos-archive-keyring.gpg] https://repo.pureos.net/pureos byzantium main" > "$1/etc/apt/sources.list"
              echo "deb [signed-by=/usr/share/keyrings/pureos-archive-keyring.gpg] https://repo.pureos.net/pureos byzantium-updates main" >> "$1/etc/apt/sources.list"
              echo "deb [signed-by=/usr/share/keyrings/pureos-archive-keyring.gpg] https://repo.pureos.net/pureos byzantium-security main" >> "$1/etc/apt/sources.list"
            ' \
            byzantium - https://repo.pureos.net/pureos \
          | xz -9 -T0 -c > pureos-byzantium-arm64.tar.xz

      - name: Push to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pureos-byzantium
          name: PureOS Byzantium
          files: |
            pureos-byzantium-arm64.tar.xz
          preserve_order: true
          make_latest: true
          overwrite: true

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
