name: "Ubuntu LTS"

on:
  schedule:
# Build Every Months
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Needed Dependencies
        run: |
          sudo apt update && sudo apt install -yq curl xz-utils
          curl -L -o /tmp/mmdebstrap.deb http://ftp.us.debian.org/debian/pool/main/m/mmdebstrap/mmdebstrap_1.5.7-3_all.deb
          sudo apt install -yq /tmp/mmdebstrap.deb
          curl -L -o /tmp/keyring.deb http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb
          sudo apt install -yq /tmp/keyring.deb
      - name: Start Building
        run: |
          dist_version="bionic"
          sudo mmdebstrap --arch=arm64 \
          --variant=apt \
          --components="main,universe,multiverse" \
          --include=locales,passwd,software-properties-common,ca-certificates,ubuntu-keyring \
          --format=directory \
          ${dist_version} \
          ubuntu \
          http://ports.ubuntu.com/ubuntu-ports
          sudo chmod -R 777 ubuntu
          tar --no-same-owner --no-same-permissions -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-${dist_version}-aarch64.tar.xz
          cp ubuntu-lts-${dist_version}-aarch64.tar.xz ubuntu-lts-aarch64.tar.xz
          
      - name: Build XFCE
        run: |
          tar --no-same-owner --no-same-permissions --exclude=dev/* -xJf ubuntu-lts-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/dev
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/proc
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/sys
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/tmp
          sudo chmod -R 777 $GITHUB_WORKSPACE/ubuntu
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/ubuntu/xfce/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/dev
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/proc
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/sys
          tar --no-same-owner --no-same-permissions --exclude=dev/* -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-xfce-aarch64.tar.xz
          cp ubuntu-lts-xfce-aarch64.tar.xz ubuntu-lts-${dist_version}-xfce-aarch64.tar.xz
          sudo rm -rf ubuntu
          
      - name: Build MATE
        run: |
          tar  --no-same-owner --no-same-permissions --exclude=dev/* -xJf ubuntu-lts-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/dev
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/proc
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/sys
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/tmp
          sudo chmod -R 777 $GITHUB_WORKSPACE/ubuntu
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/ubuntu/mate/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/dev
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/proc
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/sys
          tar  --no-same-owner --no-same-permissions --exclude=dev/* -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-mate-aarch64.tar.xz
          cp ubuntu-lts-mate-aarch64.tar.xz ubuntu-lts-${dist_version}-mate-aarch64.tar.xz
          sudo rm -rf ubuntu
          
      - name: Build LXQt
        run: |
          tar  --no-same-owner --no-same-permissions --exclude=dev/* -xJf ubuntu-lts-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/dev
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/proc
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/sys
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/tmp
          sudo chmod -R 777 $GITHUB_WORKSPACE/ubuntu
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/ubuntu/lxqt/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/dev
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/proc
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/sys
          tar  --no-same-owner --no-same-permissions --exclude=dev/* -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-lxqt-aarch64.tar.xz
          cp ubuntu-lts-lxqt-aarch64.tar.xz ubuntu-lts-${dist_version}-lxqt-aarch64.tar.xz
          sudo rm -rf ubuntu

      - name: Build LXDE
        run: |
          tar  --no-same-owner --no-same-permissions --exclude=dev/* -xJf ubuntu-lts-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/dev
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/proc
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/sys
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/tmp
          sudo chmod -R 777 $GITHUB_WORKSPACE/ubuntu
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/ubuntu/lxde/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/dev
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/proc
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/sys
          tar  --no-same-owner --no-same-permissions --exclude=dev/* -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-lxde-aarch64.tar.xz
          cp ubuntu-lts-lxde-aarch64.tar.xz ubuntu-lts-${dist_version}-lxde-aarch64.tar.xz
          sudo rm -rf ubuntu
          
      - name: Build Cinnamon
        run: |
          tar  --no-same-owner --no-same-permissions --exclude=dev/* -xJf ubuntu-lts-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/dev
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/proc
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/sys
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/tmp
          sudo chmod -R 777 $GITHUB_WORKSPACE/ubuntu
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/ubuntu/cinnamon/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/dev
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/proc
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/sys
          tar  --no-same-owner --no-same-permissions --exclude=dev/* -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-cinnamon-aarch64.tar.xz
          cp ubuntu-lts-cinnamon-aarch64.tar.xz ubuntu-lts-${dist_version}-cinnamon-aarch64.tar.xz
          sudo rm -rf ubuntu
        continue-on-error: true

      - name: Build KDE
        run: |
          tar --exclude=dev/* -xJf ubuntu-lts-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/dev
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/proc
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/sys
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/tmp
          sudo chmod -R 777 $GITHUB_WORKSPACE/ubuntu
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/ubuntu/kde/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/dev
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/proc
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/sys
          tar --no-same-owner --no-same-permissions --exclude=dev/* -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-kde-aarch64.tar.xz
          cp ubuntu-lts-kde-aarch64.tar.xz ubuntu-lts-${dist_version}-kde-aarch64.tar.xz
          sudo rm -rf ubuntu
          
      - name: Push to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ubuntu-lts-0
          name: Ubuntu LTS
          files: |
            ubuntu-lts-aarch64.tar.xz
            ubuntu-lts-*-aarch64.tar.xz
          preserve_order: true
          make_latest: false
