name: "Ubuntu LTS"

on:
  schedule:
# Build Every Week
    - cron: "0 0 * * 0"
  push:
    branches: [ 'main' ]
    paths:
      - ".github/workflows/ubuntu-lts.yml"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build-arm:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        arch: [aarch64, arm]
        release: [ resolute ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install Needed Dependencies
        run: |
          curl -L -o /tmp/mmdebstrap.deb http://ftp.us.debian.org/debian/pool/main/m/mmdebstrap/mmdebstrap_1.5.7-3_all.deb
          sudo apt install -yq /tmp/mmdebstrap.deb
          curl -L -o /tmp/keyring.deb http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb
          sudo apt install -yq /tmp/keyring.deb
          sudo dpkg --add-architecture armhf
          sudo apt update
          sudo apt install -y libc6:armhf
      - name: Start Building
        run: |
          ARCH=${{ matrix.arch }}
          case "$ARCH" in
          arm)
          ARCH="armhf"
          ;;
          aarch64)
          ARCH="arm64"
          ;;
          esac
          dist_version="${{ matrix.release }}"
          mkdir -p $GITHUB_WORKSPACE/ubuntu-lts-lts-${dist_version}-${{ matrix.arch }}
          sudo mmdebstrap \
          --arch="$ARCH" \
          --variant=apt \
          --components="main,universe,multiverse" \
          --include=locales,passwd,software-properties-common,ca-certificates \
          --format=directory \
          ${dist_version} \
          ubuntu-lts \
          http://ports.ubuntu.com/ubuntu-ports

          cat <<- EOF | sudo unshare -mpf bash -e -
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu-lts/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu-lts/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu-lts/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu-lts apt update
          sudo chroot $GITHUB_WORKSPACE/ubuntu-lts apt purge -yq --allow-remove-essential coreutils-from-uutils
          sudo chroot $GITHUB_WORKSPACE/ubuntu-lts apt purge -yq --allow-remove-essential rust-coreutils
          sudo chroot $GITHUB_WORKSPACE/ubuntu-lts apt install -yq coreutils-from-gnu
          sudo chroot $GITHUB_WORKSPACE/ubuntu-lts apt install -yq gnu-coreutils
          sudo chroot $GITHUB_WORKSPACE/ubuntu-lts apt clean
          sudo rm -rf $GITHUB_WORKSPACE/ubuntu-lts/var/lib/apt/lists/*
          EOF
          sudo tar --exclude=dev/* -cpf - ubuntu-lts | xz -9 -T0 -c > ubuntu-lts-${{ matrix.arch }}.tar.xz
          sudo rm -r ubuntu-lts

      - name: Deploy to proot-distro-desktop
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ubuntu-lts
          name: Ubuntu LTS
          files: |
            ubuntu-lts-${{ matrix.arch }}.tar.xz
          preserve_order: true
          make_latest: true

  build-amd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ x86_64 ]
        release: [ resolute ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install Needed Dependencies
        run: |
          curl -L -o /tmp/mmdebstrap.deb http://ftp.us.debian.org/debian/pool/main/m/mmdebstrap/mmdebstrap_1.5.7-3_all.deb
          sudo apt install -yq /tmp/mmdebstrap.deb
          curl -L -o /tmp/keyring.deb http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb
          sudo apt install -yq /tmp/keyring.deb
      - name: Start Building
        run: |
          ARCH=${{ matrix.arch }}
          case "$ARCH" in
          x86_64)
          ARCH="amd64"
          ;;
          esac
          dist_version="${{ matrix.release }}"
          mkdir -p $GITHUB_WORKSPACE/ubuntu-lts-lts-${dist_version}-${{ matrix.arch }}
          sudo mmdebstrap \
          --arch="$ARCH" \
          --variant=apt \
          --components="main,universe,multiverse" \
          --include=locales,passwd,software-properties-common,ca-certificates \
          --format=directory \
          ${dist_version} \
          ubuntu-lts \
          http://archive.ubuntu.com/ubuntu

          cat <<- EOF | sudo unshare -mpf bash -e -
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu-lts/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu-lts/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu-lts/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu-lts apt update
          sudo chroot $GITHUB_WORKSPACE/ubuntu-lts apt purge -yq --allow-remove-essential coreutils-from-uutils
          sudo chroot $GITHUB_WORKSPACE/ubuntu-lts apt purge -yq --allow-remove-essential rust-coreutils
          sudo chroot $GITHUB_WORKSPACE/ubuntu-lts apt install -yq coreutils-from-gnu
          sudo chroot $GITHUB_WORKSPACE/ubuntu-lts apt install -yq gnu-coreutils
          sudo chroot $GITHUB_WORKSPACE/ubuntu-lts apt clean
          sudo rm -rf $GITHUB_WORKSPACE/ubuntu-lts/var/lib/apt/lists/*
          EOF
          sudo tar --exclude=dev/* -cpf - ubuntu | xz -9 -T0 -c > ubuntu-lts-${{ matrix.arch }}.tar.xz
          sudo rm -r ubuntu

      - name: Deploy to proot-distro-desktop
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ubuntu-lts
          name: Ubuntu LTS
          files: |
            ubuntu-lts-${{ matrix.arch }}.tar.xz
          preserve_order: true
          make_latest: true
