name: "Ubuntu LTS"

on:
  schedule:
# Build Every Week
    - cron: "0 0 * * 0"
  push:
    branches: [ 'main' ]
    paths:
      - ".github/workflows/ubuntu-lts.yml"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Needed Dependencies
        run: |
          curl -L -o /tmp/mmdebstrap.deb http://ftp.us.debian.org/debian/pool/main/m/mmdebstrap/mmdebstrap_1.5.7-3_all.deb
          sudo apt install -yq /tmp/mmdebstrap.deb
          curl -L -o /tmp/keyring.deb http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb
          sudo apt install -yq /tmp/keyring.deb
          
      - name: Start Building
        run: |
          dist_version="noble"
          sudo mmdebstrap --arch=arm64 \
          --variant=apt \
          --components="main,universe,multiverse" \
          --include=locales,passwd,software-properties-common,ca-certificates,ubuntu-keyring \
          --format=tar \
          ${dist_version} \
          - \
          http://ports.ubuntu.com/ubuntu-ports \
          | xz -9 -T0 -c > tmprootfs.tar.xz
          mkdir $GITHUB_WORKSPACE/ubuntu
          tar --exclude=dev/* -xJf tmprootfs.tar.xz -C ubuntu
          sudo tar -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-aarch64.tar.xz
          sudo rm -r ubuntu

      - name: Build XFCE
        run: |
          tar -xJf ubuntu-lts-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/dev
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/proc
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/sys
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/ubuntu
          sudo chmod -R 1777 $GITHUB_WORKSPACE/ubuntu/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/ubuntu/xfce/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/dev
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/proc
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/sys
          sudo tar --exclude=dev/* -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-xfce-aarch64.tar.xz
          sudo rm -r ubuntu

      - name: Build MATE
        run: |
          tar -xJf ubuntu-lts-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/dev
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/proc
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/sys
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/ubuntu
          sudo chmod -R 1777 $GITHUB_WORKSPACE/ubuntu/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/ubuntu/mate/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/dev
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/proc
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/sys
          sudo tar --exclude=dev/* -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-mate-aarch64.tar.xz
          sudo rm -r ubuntu
          
      - name: Build LXQt
        run: |
          tar -xJf ubuntu-lts-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/dev
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/proc
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/sys
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/ubuntu
          sudo chmod -R 1777 $GITHUB_WORKSPACE/ubuntu/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/ubuntu/lxqt/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/dev
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/proc
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/sys
          sudo tar --exclude=dev/* -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-lxqt-aarch64.tar.xz
          sudo rm -r ubuntu
          
      - name: Build LXDE
        run: |
          tar -xJf ubuntu-lts-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/dev
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/proc
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/sys
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/ubuntu
          sudo chmod -R 1777 $GITHUB_WORKSPACE/ubuntu/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/ubuntu/lxde/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/dev
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/proc
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/sys
          sudo tar --exclude=dev/* -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-lxde-aarch64.tar.xz
          sudo rm -r ubuntu
          
      - name: Build Cinnamon
        run: |
          tar -xJf ubuntu-lts-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/dev
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/proc
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/sys
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/ubuntu
          sudo chmod -R 1777 $GITHUB_WORKSPACE/ubuntu/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/ubuntu/cinnamon/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/dev
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/proc
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/sys
          sudo tar --exclude=dev/* -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-cinnamon-aarch64.tar.xz
          sudo rm -r ubuntu
          
      - name: Build KDE
        run: |
          tar -xJf ubuntu-lts-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/dev
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/proc
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/sys
          sudo mkdir -p $GITHUB_WORKSPACE/ubuntu/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/ubuntu
          sudo chmod -R 1777 $GITHUB_WORKSPACE/ubuntu/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/ubuntu/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/ubuntu/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/ubuntu/sys
          sudo chroot $GITHUB_WORKSPACE/ubuntu /bin/sh -c "apt update && apt install wget -y && wget https://raw.githubusercontent.com/arfshl/proot-distro-desktop/refs/heads/main/ubuntu/kde/install.sh && sh install.sh && rm install.sh"
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/dev
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/proc
          sudo umount -l $GITHUB_WORKSPACE/ubuntu/sys
          sudo tar --exclude=dev/* -cf - ubuntu | xz -9 -T0 -c > ubuntu-lts-kde-aarch64.tar.xz
          sudo rm -r ubuntu

      - name: Deploy to proot-distro-desktop
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ubuntu-lts
          name: Ubuntu LTS
          files: |
            ubuntu-lts-aarch64.tar.xz
            ubuntu-lts-*-aarch64.tar.xz
          preserve_order: true
          make_latest: true
